name: Azure What-If
on:
  pull_request:
      types: [opened, synchronize]
      paths:
        - bicep/**
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  what-if:
    environment: Azure-PR
    runs-on: ubuntu-24.04
    steps:

      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: What-If Deployment
        uses: azure/bicep-deploy@v2
        with:
          type: deployment
          operation: whatIf
          validation-level: providerNoRbac
          name: demo-deployment
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          scope: resourceGroup
          resource-group-name: demo-whatif-gh-rg
          template-file: ./bicep/demo/main.bicep